server:
  port: 8101

# Configuration need to whr-worker knows Eureka server
eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
    refresh:
      enable: true

spring:
  application:
    name: hr-payroll
  devtools:
    restart:
      enabled: true