server:
  port: 8101

# Configuration need to hr-payroll connect to Eureka server
eureka:
  client:
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 10

spring:
  application:
    name: hr-payroll
  devtools:
    restart:
      enabled: true

