server:
  port: ${PORT:0} # configure random port

# Configuration need to hr-worker connect to Eureka Server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}} # random instance, necessary to multiples services instances
spring:
  application:
    name: hr-worker
  devtools:
    restart:
      enabled: true

#Database configuration
  datasource:
    url: jdbc:h2:mem:testdb
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
    defer-datasource-initialization: true